pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.kikugie.dev/releases" }
        maven { url = "https://maven.kikugie.dev/snapshots" }
    }
}

plugins {
    id "dev.kikugie.stonecutter" version "0.9.8"
}

stonecutter {
    kotlinController = false
    centralScript = "build.gradle"

    create(getRootProject()) {
        versions '26.4', '26.3', '26.2', '26.1'
    }
}

rootProject.name = "mc-autotool"
