plugins {
    id 'dev.kikugie.stonecutter'
}

stonecutter.active '26.4'

tasks.register('buildAll') {
    group = 'build'
    description = 'Builds all Stonecutter versions'
    dependsOn stonecutter.tasks.named('build')
}

subprojects { subproject ->
    tasks.register("run${subproject.name}") {
        group = 'fabric'
        description = "Runs Minecraft client for ${subproject.name}"
        dependsOn ":${subproject.name}:runClient"
    }
}

def VISIBLE_TASKS = [
    'buildAll',
    'clean',
    'run26.4',
    'run26.3',
    'run26.2',
    'run26.1'
] as Set

gradle.projectsEvaluated {
    allprojects { p ->
        p.tasks.configureEach { task ->
            if (!VISIBLE_TASKS.contains(task.name)) {
                task.group = null
            }
        }
    }
}



