name: Publish

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      version:
        description: 'Minecraft version to publish'
        required: true
        default: 'all'
        type: choice 
        options:
          - 'all'
          - '26.4'
          - '26.3'
          - '26.2'
          - '26.1'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event.inputs.version }}" == "all" ]; then
            echo 'matrix=["26.4", "26.3", "26.2", "26.1"]' >> $GITHUB_OUTPUT
          else
            echo 'matrix=["${{ github.event.inputs.version }}"]' >> $GITHUB_OUTPUT
          fi

  publish:
    needs: prepare
    name: Publish for Minecraft ${{ matrix.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build mod
        run: |
          curl https://mise.run | sh
          mise exec java@25 -- ./gradlew :${{ matrix.version }}:build
          mv versions/${{ matrix.version }}/build/libs/$(ls versions/${{ matrix.version }}/build/libs/ | head -n 1) autotool.jar
          echo "JAR_PATH=autotool.jar" >> $GITHUB_ENV

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.JAR_PATH }}
          tag: ${{ matrix.version }}
          target_commit: master
          overwrite: true
          make_latest: ${{ matrix.version == '26.4' }}
          release_name: Autotool for Minecraft ${{ matrix.version }}
